### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by ExtazUxy** [Mekolaos/Aternos-On-Discord#17]
Hello, after nearly 8 hours of trying to install your aternos bot finnally it is alive i do have the bot on my server but when i try the command --launch server, the bot says "Launching Server...
An error occurred. Either the status server is not responding or you didn't set the server name correctly.

Trying to launch the server anyways."
But nothing is launching please help me.

**Comment by brandonnly** [comment]
1. Make sure your Aternos credentials were correct
2. Could you send your console output when the error occurs?

**Comment by ExtazUxy** [comment]
My aternos credentials are correct because the bot is able to give me the name the number of slots etc of my server.
`D:\Desktop\Aternos-On-Discord-master>py Bot.py

DevTools listening on ws://127.0.0.1:53208/devtools/browser/001f7a1f-91ee-4027-be35-aaf5c3b15f0c
Headless Tab Ready
The bot is logged in as chabsurvie#3650
[1221/230005.488:INFO:CONSOLE(3)] "fun-hooks: referenced 'registerAdserver' but it was never created", source: https://cdn.snigelweb.com/prebid/latest/prebid.js (3)
[1221/230005.940:INFO:CONSOLE(1)] "%cAdConsent display: inline-block; color: #fff; background: #ffe600; padding: 1px 4px; border-radius: 3px; WARN: (adconsent) Command 'addCustomVendor' is deprecated and will be removed soon.", source: https://cdn.snigelweb.com/adconsent/adconsent.js (1)
[1221/230005.940:INFO:CONSOLE(1)] "%cAdConsent display: inline-block; color: #fff; background: #ffe600; padding: 1px 4px; border-radius: 3px; WARN: (adconsent) Command 'setGlobalVendorListURI' has been removed from the API.", source: https://cdn.snigelweb.com/adconsent/adconsent.js (1)
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Uxy_\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "Bot.py", line 73, in on_message
    await start_server()
  File "D:\Desktop\Aternos-On-Discord-master\connect_and_launch.py", line 33, in start_server
    element.click()
  File "C:\Users\Uxy_\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Uxy_\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Uxy_\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Uxy_\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=87.0.4280.88)`

**Comment by brandonnly** [comment]
Try change `headless = True` to `headless = False` on line 16 of `connect_and_launch.py` and run the bot again.

It should open up a chrome tab. Screenshot the page when you try to launch your server so I can see where it gets stuck at.

**Comment by ExtazUxy** [comment]
![image](https://user-images.githubusercontent.com/64648068/102921616-f4512180-448c-11eb-82c7-7ac588df74ca.png)

**Comment by ExtazUxy** [comment]
![image](https://user-images.githubusercontent.com/64648068/102921755-30848200-448d-11eb-9daf-4d8eef78571b.png)
stuck on the TCU

**Comment by brandonnly** [comment]
Got it! I didn't get that when testing as I'm not from the EU. I'll try to get an update out soon that should fix this.

**Comment by Mekolaos** [comment]
Was this the first time you connected to that aternos account ?

**Comment by brandonnly** [comment]
@ExtazUxy If you could get the Xpath of the accept button, I can patch it.

**Comment by ExtazUxy** [comment]
@brandonnly hey sorry man for not responding faster i had a busy year, but now im in vacation do you have a discord or something ?

**Comment by pritam20ps05** [comment]
please once check my project on this https://github.com/pritam20ps05/mcscraper
it works pretty well and works 98% of the time my server personally uses it.
