### ISSUE TITLE
Umm... This keeps happening

### ISSUE THREAD

**Issue by SnapMC** [Mekolaos/Aternos-On-Discord#19]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1895, in __call__
    return self.func(*args)
  File "C:\Users\Manimation\Desktop\Aternos-On-Discord-master\Configure.py", line 36, in <lambda>
    save_button['command'] = lambda: save_configuration(bot_token_entry,
  File "C:\Users\Manimation\Desktop\Aternos-On-Discord-master\Configure.py", line 50, in save_configuration
    with open(".env", "w") as f:
PermissionError: [Errno 13] Permission denied: '.env'

**Comment by Thebestandgreatest** [comment]
I had this error, I just closed the command prompt and opened a new one and everything worked.

**Comment by Mekolaos** [comment]
I'm guessing it's because it's trying to create the file in the desktop and you might not have permissions ? Haven't tried it, but I assume that's what's happening.
