### ISSUE TITLE
Script Breaks When Calling Launch Server and Server Info

### ISSUE THREAD

**Issue by O-Luhishi** [Mekolaos/Aternos-On-Discord#21]
Stacktrace for `Server Info`:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "D:/My Document/Programming/Python/Aternos-On-Discord/Bot.py", line 83, in on_message
    ip, status, players, software, version = get_server_info()
  File "D:\My Document\Programming\Python\Aternos-On-Discord\connect_and_launch.py", line 77, in get_server_info
    return server_ip, get_status(), get_number_of_players(), software, version
  File "D:\My Document\Programming\Python\Aternos-On-Discord\connect_and_launch.py", line 64, in get_number_of_players
    element = driver.find_element_by_xpath('//*[@id="players"]')
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="players"]"}
  (Session info: headless chrome=88.0.4324.104)

```

Stacktrace for `Server Launch:`

```
    await start_server()
  File "D:\My Document\Programming\Python\Aternos-On-Discord\connect_and_launch.py", line 33, in start_server
    element.click()
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div id="start" class="btn btn-huge btn-success">...</div> is not clickable at point (387, 396). Other element would receive the click: <div class="sn-footer-tab">...</div>
  (Session info: headless chrome=88.0.4324.104)
```

Tested on Main branch, Python 3.7 - I suspect Aternos have changed something in their UI maybe?

**Comment by O-Luhishi** [comment]
@Thebestandgreatest Not to be a pain, but bug fix #22 does indeed fix Server Status, however `--launch server` & `--stop server` is still broken. Latest stracktrace: 
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "D:/My Document/Programming/Python/Aternos-On-Discord/Bot.py", line 47, in on_message
    await start_server()
  File "D:\My Document\Programming\Python\Aternos-On-Discord\connect_and_launch.py", line 33, in start_server
    element.click()
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\My Document\Programming\Python\Aternos-On-Discord\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div id="start" class="btn btn-huge btn-success">...</div> is not clickable at point (387, 396). Other element would receive the click: <div class="sn-footer-tab">...</div>
  (Session info: headless chrome=88.0.4324.104)
```

**Comment by Thebestandgreatest** [comment]
I didn't have a problem with `--launch server` or `--stop server` after the fix. Everything worked fine for me.

**Comment by O-Luhishi** [comment]
> I didn't have a problem with `--launch server` or `--stop server` after the fix. Everything worked fine for me.

Hmm that's odd. I'm going to give it a try again and see if I can run it on another device. Would you have any idea from the logs where this might be going wrong?

**Comment by brandonnly** [comment]
Heyo! If you can get the Xpath of the Accept button for me, I can implement a fix.
