### ISSUE TITLE
Doesn't Work on RPI 3B

### ISSUE THREAD

**Issue by AzamServer** [Mekolaos/Aternos-On-Discord#23]
Hi,
This bot doesn't work on the RPI 3B. Does this bot support ARM? Using Python3 and PIP3. Accessing RPI using SSH.

**Comment by AzamServer** [comment]
Error:

Traceback (most recent call last):
  File "Bot.py", line 8, in <module>
    from connect_and_launch import get_status, get_number_of_players
  File "/etc/discordbots/SMPBot/connect_and_launch.py", line 25, in <module>
    driver = webdriver.Chrome(options=options, executable_path=binary_path)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.7/dist-packages/chromedriver_py/chromedriver_linux64'

**Comment by brandonnly** [comment]
Haven't tested it on a Rasberry Pi, but I would assume it would require a different chromedriver package for ARM.

Just got myself one though so I'll try play around with it.

**Comment by AzamServer** [comment]
Thanks! Please keep me updated!

**Comment by brandonnly** [comment]
I've been able to get it to run but think I am running into the same issue at #21 wherein it gets stuck at the cookies screen. I can't tell for sure because I don't have GUI access to my Pi.

Here's what I did:

### Raspberry Pi Setup

Before following the instructions, make sure you have the following installed: 
- `sudo apt-get install libxml2-dev libxslt-dev python-dev`
- `sudo apt-get install python3-lxml python-lxml`
- `sudo apt-get install python3-wheel`
- `sudo apt-get install python3-tk`


1. Git clone this repository
2. Install it using `pip3 install -r requirements.txt` inside the folder
   - **NOTE**: This may take a while even on higher end Pi's
3. 3. Setup a [Bot Account](https://discordpy.readthedocs.io/en/latest/discord.html)
   - You'll need the Bot Token for setting up the Bot
4. If you don't have a GUI:
   - Create a `.env` file in the following format:
      ```dotenv
        BOT_TOKEN= DISCORD_BOT_TOKEN
        USERNAME_C= ATERNOS_USERNAME
        PASSWORD_C= ATERNOS_PASSWORD
      ```
4. Setup Chromium 
   1. `sudo apt-get install chromium-browser`
   2. `sudo apt-get install chromium-chromedriver`
   3. In `connect_and_launch.py`, change driver executable path to `'/usr/lib/chromium-browser/chromedriver'`
5. Run the bot with `python3 Bot.py`

**Comment by brandonnly** [comment]
Nevermind it was an error in the code, working flawlessly now for me on my RPi 4B running Ubuntu 20.04 LTS server.

Made a PR for it (#25). You can use my repo in the meantime.

**Comment by AzamServer** [comment]
Ok, thanks!
