### ISSUE TITLE
Doesn't Work on Google Cloud VM

### ISSUE THREAD

**Issue by AzamServer** [Mekolaos/Aternos-On-Discord#24]
Hi,
This bot doesn't work on Google Cloud VM. Does this bot run in a CLI environment? Using Python3 and PIP3. Accessing Google Cloud VM using SSH.

**Comment by AzamServer** [comment]
Error:

Traceback (most recent call last):
  File "Bot.py", line 8, in <module>
    from connect_and_launch import get_status, get_number_of_players
  File "/home/azamemail101/SMPBot/connect_and_launch.py", line 25, in <module>
    driver = webdriver.Chrome(options=options, executable_path=binary_path)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by brandonnly** [comment]
Not sure what the error is from the error message but, from the README:

### Cloud Hosting Note
Cloud hosting this bot would require some workarounds as Aternos recognizes you are connecting from a data center and prompts for a captcha test.

**Comment by AzamServer** [comment]
I read that error, but I doubt it's that. The error says Chrome crashed. Any ideas?

**Comment by brandonnly** [comment]
After some digging, you may need to add these options to `connect_and_launch.py`

```py
options.add_argument('--disable-extensions')
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')
```

**Comment by AzamServer** [comment]
Ok, thanks!

**Comment by AzamServer** [comment]
Getting an error, but it looks like it's because I am using an google cloud VM.

**Comment by brandonnly** [comment]
If it's a selenium error, it's likely because Aternos is prompting a captcha test.
