### ISSUE TITLE
idk what to do after this

### ISSUE THREAD

**Issue by Exustine12** [Mekolaos/Aternos-On-Discord#29]
i installed chromedriver version 89 and chrome beta 89 but the bot wont start and this error keep on popping up

C:\Users\HET BHUVA\OneDrive\Desktop\BOT MAKING\Aternos-On-Discord-master>python bot.py

DevTools listening on ws://127.0.0.1:60562/devtools/browser/053210ff-e277-4eba-b0da-e4f4e2d5375c
[0224/111105.006:ERROR:browser_gpu_channel_host_factory.cc(168)] Failed to launch GPU process.
Traceback (most recent call last):
  File "C:\Users\HET BHUVA\OneDrive\Desktop\BOT MAKING\Aternos-On-Discord-master\bot.py", line 11, in <module>
    from connect_and_launch import get_status, get_number_of_players, \
  File "C:\Users\HET BHUVA\OneDrive\Desktop\BOT MAKING\Aternos-On-Discord-master\connect_and_launch.py", line 28, in <module>
    driver = webdriver.Chrome(options=options, executable_path=binary_path)
  File "C:\Users\HET BHUVA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\HET BHUVA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\HET BHUVA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\HET BHUVA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\HET BHUVA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 88.0.4324.190 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

please help me

**Comment by brandonnly** [comment]
Heya, you should be using Chromedriver version 88, which is what is in `requirements.txt`
