### ISSUE TITLE
readme is unclear

### ISSUE THREAD

**Issue by Thebestandgreatest** [Mekolaos/Aternos-On-Discord#3]
I am trying to setup the bot, but am having issues with step 3. I keep getting wrong path errors when i try to run the command
```    
python.exe Bot.py
```
All I get out of the console is this
```
 File "C:\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Bot.py", line 7, in <module>
    from connect_and_launch import start_server, get_status, stop_server
  File "C:\Users\AdamParke\Downloads\Aternos-On-Discord-master(1)\Aternos-On-Discord-master\connect_and_launch.py", line 28, in <module>
    driver = webdriver.Chrome(options=options)
  File "C:\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

**Comment by Mekolaos** [comment]
Hello !
I will update the readme asap.
The solution is to install the [chrome driver](https://sites.google.com/a/chromium.org/chromedriver/downloads) from this link.
Feel free to tell me if there's any other issue !

**Comment by Mekolaos** [comment]
Updated the project so the chromedriver installs itself.

**Comment by Thebestandgreatest** [comment]
Thank you for your help!

**Comment by Mekolaos** [comment]
No worries :D
