### ISSUE TITLE
[Bug] [--launch] - Element <div id="start" class="btn btn-huge btn-success">...</div> is not clickable at point (388, 396).

### ISSUE THREAD

**Issue by Aeris1One** [Mekolaos/Aternos-On-Discord#32]
## Some logs at first
```
Ignoring exception in command launch:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "Bot.py", line 70, in launch
    await start_server()
  File "/home/ubuntu/Aternos-On-Discord/connect_and_launch.py", line 36, in start_server
    element.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div id="start" class="btn btn-huge btn-success">...</div> is not clickable at point (388, 396). Other element would receive the click: <div class="sn-footer-tab">...</div>
  (Session info: headless chrome=89.0.4389.72)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ElementClickInterceptedException: Message: element click intercepted: Element <div id="start" class="btn btn-huge btn-success">...</div> is not clickable at point (388, 396). Other element would receive the click: <div class="sn-footer-tab">...</div>
  (Session info: headless chrome=89.0.4389.72)
```
## Context
Installed the bot on a RPi 4B 8Gb (with Ubuntu 20.04 LTS), worked since `--launch` which throw the error above.

**Comment by brandonnly** [comment]
If it's the first time your logging into this account, you may need to go in manually and accept the TOS agreement.

Does this happen all the time or only after a while of the bot being on? Found that this happens to me after a few days of the bot being online, due to the browser crashing. A quick restart fixes it for me.

**Comment by Aeris1One** [comment]
The account already accepted TOS on my computer, does they needs to be accepted on each browser connecting to the account? It was the first time running the bot, will have another try

**Comment by brandonnly** [comment]
Not entirely sure when it happens TBH, haven't been able to get it to pop up for myself so I can't fix it.

**Comment by pritam20ps05** [comment]
please once check my project on this https://github.com/pritam20ps05/mcscraper
it works pretty well and works 98% of the time my server personally uses it.
