### ISSUE TITLE
Only --help is working

### ISSUE THREAD

**Issue by Haadastic** [Mekolaos/Aternos-On-Discord#37]

**Comment by Haadastic** [comment]
When i type --players it says 0 players are online while thats false when there are 2 players playing

**Comment by G-Trip** [comment]
somehow your xpath is wrong. try to locate your web element by id, it is more reliable than xpath.
browser.find_element(By.ID,"nope")

**Comment by Hallohannes123** [comment]
> somehow your xpath is wrong. try to locate your web element by id, it is more reliable than xpath.
> browser.find_element(By.ID,"nope")

I'm having the same issue, can you please explain what to do a bit simpler, I can't quite follow.

Extra info: 
- When I do headless=false in the chrome tab it shows the error 403 login
- Do I need to be the owner of the server?
The aternos-username is NOT the same as the beginning of the server ip as I am accessing another users server (with full permission tho)

**Comment by Hallohannes123** [comment]
Update:
I looked into the documentation of selenium a bit to understand the code and the problem is not in the code, the errors are just because the login outputs this
![image](https://user-images.githubusercontent.com/49411685/114209982-8a875580-995f-11eb-8d14-e813a9ec74c2.png)
`It says "an error occured"`

so when it tries to continue it can't find the correct Buttons.
What could cause this error?
When I login manually through a normal window in chrome it works.

**Comment by Hallohannes123** [comment]
`Disclaimer: I can not code. I just read some documentations on the web and looked at the code in the script, Therefore the code I wrote is probably bad, but as good as I could do it`

I fixed this issue.
The error means it detected that its an automated script.
![image](https://user-images.githubusercontent.com/49411685/114271794-874da180-9a13-11eb-899c-525cccd429b5.png)
Adding the marked line fixes this issue.
A new issue showed up because there was a cookie banner showing up
This Is kinda hard to remove tho as it sometimes shows up early, before the bot clicks on the server in the serverlist and sometimes after already having clicked on it.
![image](https://user-images.githubusercontent.com/49411685/114273394-25446a80-9a1a-11eb-9a45-b8a43299cf89.png)
I did this and it kinda works, but not always :(


Even if it works, I have a new issue. If the bot starts and logs in correctly I can't execute any commands.
Heres the error message when running --stop

> Ignoring exception in command stop:
> Traceback (most recent call last):
>   File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "E:\Users\migra\Dokumente\GitHub\Aternos-On-Discord\Bot.py", line 126, in stop
>     server_status = get_status()
>   File "E:\Users\migra\Dokumente\GitHub\Aternos-On-Discord\connect_and_launch.py", line 56, in get_status
>     return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
>     return self.execute(Command.FIND_ELEMENT, {
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
>   (Session info: chrome=89.0.4389.114)
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
>     await ctx.command.invoke(ctx)
>   File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
>     await injected(*ctx.args, **ctx.kwargs)
>   File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
>   (Session info: chrome=89.0.4389.114)

**Comment by Hallohannes123** [comment]
> When i type --players it says 0 players are online while thats false when there are 2 players playing

Try replacing all "nope"'s with "read-out-tos"

**Comment by SalsaDeliveryMan** [comment]
> ![image](https://user-images.githubusercontent.com/49411685/114320929-abdf7180-9b18-11eb-9492-ddcada6bf96f.png)

I've never really coded before and after changing the code to this(^) and running the bot, it gives me a TabError and says that I have an "inconsistent use of tabs and spaces in indentation". I tried to line up the code the best I could by adding spaces, but I must have done something wrong.

**Comment by pritam20ps05** [comment]
please once check my project on this https://github.com/pritam20ps05/mcscraper
it works pretty well and works 98% of the time my server personally uses it.
