### ISSUE TITLE
Is something wrong?

### ISSUE THREAD

**Issue by NikoIsThere** [Mekolaos/Aternos-On-Discord#38]
the bot already run as ok, theres no problems when login.

the problem that the bot only response with --help
them other command wont work
i try to make headless=false
it already in a server page (no login again) but unable to start or check status
i already instal with pip install -r requirements.txt
i also already set up the info of the account (aternos account and bot discord token)

this is the log 

----------------------------------------------------------------------------------------------------------------------------------------------
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS D:\program files\Python\Aternos-On-Discord-master> python Bot.py

DevTools listening on ws://127.0.0.1:60427/devtools/browser/7c794f75-0c94-4c70-8798-f2bb29475397
[WARNING] 2021-04-02 10:23:20,376 - PyNaCl is not installed, voice will NOT be supported
[INFO] 2021-04-02 10:23:20,378 - logging in using static token
[INFO] 2021-04-02 10:23:25,070 - Shard ID None has sent the IDENTIFY payload.
[INFO] 2021-04-02 10:23:25,842 - Shard ID None has connected to Gateway: ["gateway-prd-main-p9r5",{"micros":83217,"calls":["discord-sessions-prd-2-47",{"micros":81825,"calls":["start_session",{"micros":50841,"calls":["api-prd-main-tc46",{"micros":44533,"calls":["get_user",{"micros":2374},"add_authorized_ip",{"micros":2128},"get_guilds",{"micros":10346},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":27370,"calls":[]}]}]}] (Session ID: 5bde6202c5c32c9a776c66409e82cc32).
[11572:6484:0402/102326.311:ERROR:device_event_log_impl.cc(214)] [10:23:26.311] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from 
node connection: A device attached to the system is not functioning. (0x1F)
[11572:6484:0402/102326.313:ERROR:device_event_log_impl.cc(214)] [10:23:26.313] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from 
node connection: A device attached to the system is not functioning. (0x1F)
[INFO] 2021-04-02 10:24:00,671 - Aternos Tab Loaded
[INFO] 2021-04-02 10:24:00,672 - The bot is logged in as: Gabuter's MC Bot#7042
[WARNING] 2021-04-02 10:24:23,132 - Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "Bot.py", line 183, in <module>
    bot.run(BOT_TOKEN)
  File "D:\program files\Python\lib\site-packages\discord\client.py", line 708, in run
    loop.run_forever()
  File "D:\program files\Python\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "D:\program files\Python\lib\asyncio\base_events.py", line 1758, in _run_once
    handle._run()
  File "D:\program files\Python\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\program files\Python\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "Bot.py", line 153, in serverStatus
    server_status = get_status()
  File "D:\program files\Python\Aternos-On-Discord-master\connect_and_launch.py", line 53, in get_status
    return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "D:\program files\Python\lib\site-packages\urllib3\request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "D:\program files\Python\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\program files\Python\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\program files\Python\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "D:\program files\Python\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\program files\Python\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\program files\Python\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\program files\Python\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\program files\Python\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)

Unhandled exception in internal background task 'serverStatus'.
Traceback (most recent call last):
  File "D:\program files\Python\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "Bot.py", line 153, in serverStatus
    server_status = get_status()
  File "D:\program files\Python\Aternos-On-Discord-master\connect_and_launch.py", line 53, in get_status
    return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: chrome=89.0.4389.114)

[INFO] 2021-04-02 10:24:32,886 - Refreshed browser
[INFO] 2021-04-02 10:24:32,888 - Timed out receiving packet. Attempting a reconnect.
[INFO] 2021-04-02 10:24:32,889 - Got a request to RESUME the websocket.
[INFO] 2021-04-02 10:24:37,171 - Shard ID None has sent the RESUME payload.
[INFO] 2021-04-02 10:24:38,113 - Shard ID None has successfully RESUMED session 5bde6202c5c32c9a776c66409e82cc32 under trace ["gateway-prd-main-nwmd",{"micros":1594,"calls":["discord-sessions-prd-2-47",{"micros":47}]}].
Ignoring exception in command status:
Traceback (most recent call last):
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "Bot.py", line 110, in status
    await ctx.send(f"The server is {get_status()}")
  File "D:\program files\Python\Aternos-On-Discord-master\connect_and_launch.py", line 53, in get_status
    return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: chrome=89.0.4389.114)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: chrome=89.0.4389.114)

Ignoring exception in command launch:
Traceback (most recent call last):
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "Bot.py", line 66, in launch
    server_status = get_status()
  File "D:\program files\Python\Aternos-On-Discord-master\connect_and_launch.py", line 53, in get_status
    return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: chrome=89.0.4389.114)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: chrome=89.0.4389.114)

Ignoring exception in command info:
Traceback (most recent call last):
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "Bot.py", line 121, in info
    await ctx.send(embed=server_info_embed())
  File "D:\program files\Python\Aternos-On-Discord-master\embeds.py", line 7, in server_info_embed
    ip, status, players, software, version, tps = get_server_info()
  File "D:\program files\Python\Aternos-On-Discord-master\connect_and_launch.py", line 106, in get_server_info
    return get_ip(), get_status(), get_number_of_players(), \
  File "D:\program files\Python\Aternos-On-Discord-master\connect_and_launch.py", line 75, in get_ip
    return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\program files\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[1]"}
  (Session info: chrome=89.0.4389.114)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\program files\Python\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[1]"}
  (Session info: chrome=89.0.4389.114)

----------------------------------------------------------------------------------------------------------------------------------------------

can someone help me? im newbie to xpath and stuffs,any help is really appreciated.

**Comment by pritam20ps05** [comment]
please once check my project on this https://github.com/pritam20ps05/mcscraper
it works pretty well and works 98% of the time my server personally uses it.
