### ISSUE TITLE
Unable to locate element: @id=nope

### ISSUE THREAD

**Issue by l0nkDev** [Mekolaos/Aternos-On-Discord#49]
Whenever i try to run any command besides --help and --players the console outputs the following error
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/l0nk/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/l0nk/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/l0nk/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: chrome=90.0.4430.93)
```

i've seen in connect and launch.py that @id=nope is searched in a lot of functions, so i can't really tell which one is the one failing, or if they're all failing to locate nope.

**Comment by jaison-jai-john** [comment]
did u check till where selinium manages to reach? i changed the headless variable to False in connect_and_launch.py and found that the scraper stops at the login page since aternos sends back a 403 alert.
