### ISSUE TITLE
stuck on logging into discord

### ISSUE THREAD

**Issue by MasonTheMong** [Mekolaos/Aternos-On-Discord#53]
it just comes up with...

DevTools listening on ws://127.0.0.1:53641/devtools/browser/621da020-6112-47e1-b5e1-81c9e1fb4ce0
[WARNING] 2021-06-02 10:38:53,054 - PyNaCl is not installed, voice will NOT be supported
[INFO] 2021-06-02 10:38:53,062 - logging in using static token
[INFO] 2021-06-02 10:38:53,671 - Shard ID None has sent the IDENTIFY payload.
[INFO] 2021-06-02 10:38:53,841 - Shard ID None has connected to Gateway: ["gateway-prd-main-9884",{"micros":64544,"calls":["discord-sessions-blue-prd-2-171",{"micros":63436,"calls":["start_session",{"micros":31682,"calls":["api-prd-main-6516",{"micros":28408,"calls":["get_user",{"micros":2851},"add_authorized_ip",{"micros":1325},"get_guilds",{"micros":4152},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":31201,"calls":[]}]}]}] (Session ID: 82348bbe5791c5c8b3b28399c3f33126).
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\Bot.py", line 51, in on_ready
    connect_account()  # logs into aternos
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\connect_and_launch.py", line 124, in connect_account
    element = driver.find_element_by_css_selector('body > div > main > section'
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body > div > main > section> div > div.servers.single > div > div.server-body"}
  (Session info: headless chrome=90.0.4430.212)

Ignoring exception in command launch:
Traceback (most recent call last):
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\Bot.py", line 66, in launch
    server_status = get_status()
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\connect_and_launch.py", line 53, in get_status
    return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: headless chrome=90.0.4430.212)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[3]/div[1]/div/span[2]/span"}
  (Session info: headless chrome=90.0.4430.212)

Ignoring exception in command info:
Traceback (most recent call last):
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\Bot.py", line 121, in info
    await ctx.send(embed=server_info_embed())
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\embeds.py", line 7, in server_info_embed
    ip, status, players, software, version, tps = get_server_info()
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\connect_and_launch.py", line 106, in get_server_info
    return get_ip(), get_status(), get_number_of_players(), \
  File "C:\Users\FiercePC\Downloads\bot\Aternos-On-Discord-master\connect_and_launch.py", line 75, in get_ip
    return driver.find_element_by_xpath('//*[@id="nope"]/main/section/div['
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[1]"}
  (Session info: headless chrome=90.0.4430.212)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\FiercePC\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="nope"]/main/section/div[3]/div[1]"}
  (Session info: headless chrome=90.0.4430.212)

**Comment by pritam20ps05** [comment]
please once check my project on this https://github.com/pritam20ps05/mcscraper
it works pretty well and works 98% of the time my server personally uses it.
