### ISSUE TITLE
Error when executing Bot.py

### ISSUE THREAD

**Issue by learle868** [Mekolaos/Aternos-On-Discord#76]
I use Debian 11 and have the newest version of python installed (3.9). After cloning I executed Bot.py and this error came. I hope you can help me. Thank you.

Crash report:
Traceback (most recent call last):
  File "/home/discordbot/Aternos-On-Discord/Bot.py", line 23, in <module>
    launch_config()
  File "/home/discordbot/Aternos-On-Discord/Configure.py", line 8, in launch_config
    window = tk.Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by pritam20ps05** [comment]
please once check my project on this https://github.com/pritam20ps05/mcscraper
it works pretty well and works 98% of the time my server personally uses it.
