### ISSUE TITLE
can_fire_async

### ISSUE THREAD

**Issue by daxil34** [Mekolaos/Aternos-On-Discord#8]
DevTools listening on ws://127.0.0.1:53661/devtools/browser/7ef92895-74fe-4a06-87df-d2ff2b8010df
Traceback (most recent call last):
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 256, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 220, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\Bot.py", line 57, in <module>
    client.run('UsNHd5JEiiOTM54fMK889KtsqYCE4JJF')
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 584, in start
    await self.login(*args, bot=bot)
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 442, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 260, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022B7BE84430>
Traceback (most recent call last):
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\daxil\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'can_fire_async' was never awaited

**Comment by Thebestandgreatest** [comment]
Check that your bot token is correct. I tried entering an invalid token and I got the same error

**Comment by JendaPlayz** [comment]
Hi there im kinda having a similar problem 

`DevTools listening on ws://127.0.0.1:51637/devtools/browser/9dda76d0-34c0-45f5-a3f1-2fdf2779d961
Traceback (most recent call last):
  File "Bot.py", line 78, in <module>
    client.run(BOT_TOKEN)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 463, in _connect
    await self.ws.poll_event()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\gateway.py", line 425, in received_message
    func(data)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\state.py", line 750, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\state.py", line 725, in _get_create_guild
    guild._from_data(data)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\guild.py", line 290, in _from_data
    self._sync(guild)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\guild.py", line 321, in _sync
    self._add_channel(CategoryChannel(guild=self, data=c, state=self._state))
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\channel.py", line 726, in __init__
    self._update(guild, data)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\channel.py", line 737, in _update
    self._fill_overwrites(data)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
sys:1: RuntimeWarning: coroutine 'can_fire_async' was never awaited`

**Comment by Thebestandgreatest** [comment]
Again, check that your config is correct. If you don't have the proper token or the proper login errors will happen.

**Comment by JendaPlayz** [comment]
Im copy and pasting all info in there and still getting the same error
